version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: tessera-redis
    ports:
      - '127.0.0.1:6379:6379'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3

  mongo:
    image: mongo:7
    container_name: tessera-mongo
    ports:
      - '127.0.0.1:27017:27017'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.adminCommand("ping")']
      interval: 10s
      timeout: 5s
      retries: 3